In [1]:
a = [1.0, 2.0, 1.0]

In [2]:
a[0]

1.0

In [4]:
a[2] = 3.0
a

[1.0, 2.0, 3.0]

In [5]:
import torch
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [6]:
a[1]

tensor(1.)

In [7]:
float(a[1])

1.0

In [8]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [10]:
points = torch.zeros(6) 
points[0] = 4.0 
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0
points

tensor([4., 1., 5., 3., 2., 1.])

In [11]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [12]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [13]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [14]:
points.shape

torch.Size([3, 2])

In [15]:
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [16]:
points = torch.FloatTensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [17]:
points[0, 1]

tensor(1.)

In [18]:
points[0]

tensor([4., 1.])

In [19]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage() # storage 将tensor以一维tensor连续的储存，因此上面的二维tensor再经过storage后变为一维

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [20]:
points_storage = points.storage()
points_storage[0]

4.0

In [21]:
points.storage()[1]

1.0

In [22]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_storage = points.storage()
points_storage[0] = 2.0
points
## 这里证明了storage()和原始tensor共享存储，即改变其中一个会导致另一个也同样发生变化

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

In [23]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point.storage_offset()
# storage_offset 代表从存储空间到当前选中tensor数据的偏移量

2

In [24]:
second_point.size()

torch.Size([2])

In [25]:
second_point.shape

torch.Size([2])

In [26]:
points.stride()
## stride 步长代表各维度上从一个数据到邻近数据需要经过的距离，其中stride的维度是从外向内逐层递增的。

(2, 1)

In [28]:
second_point = points[1]
second_point.size()

torch.Size([2])

In [29]:
second_point.storage_offset()

2

In [30]:
second_point.stride()

(1,)

In [31]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point[0] = 10.0
points
## 共享storage的又一例子，并不复制tensor

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [32]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points
## 若复制tensor，需使用clone

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [33]:
points_t = points.t()
points_t
## tensor的转置

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [34]:
id(points.storage()) == id(points_t.storage())
## tensor的转置不改变内存地址

True

In [35]:
points.stride()

(2, 1)

In [36]:
points_t.stride()

(1, 2)

In [37]:
some_t = torch.ones(3, 4, 5)
transpose_t = some_t.transpose(0, 2)
some_t.shape

torch.Size([3, 4, 5])

In [38]:
transpose_t.shape
# 这里演示了如何将tensor进行形状的改变，这里transpose对换了0，2两个维度，如果对数据是否发生对应改变有疑问可以自行验证，但如果开动脑筋可以想象在内存不改变的情况下。这种转置其实只是对index，stride的顺序改变，也即对索引表的改变。

torch.Size([5, 4, 3])

In [39]:
some_t.stride()

(20, 5, 1)

In [40]:
transpose_t.stride()

(1, 5, 20)

In [41]:
points.is_contiguous()
## 判断tensor是否在内存中是否以 C-order 为顺序连续保存的，会造成不连续的操作包括narrow，transpose

True

In [42]:
points_t.is_contiguous()

False

In [43]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [44]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [45]:
points_t.stride()
# stride变换顺序，即改变索引表

(1, 2)

In [46]:
points_t_cont = points_t.contiguous()
points_t_cont

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [47]:
points_t_cont.stride()
# 如果连续情况下，stride应该如下

(3, 1)

In [48]:
points_t_cont.storage()

 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.FloatStorage of size 6]

In [49]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

In [50]:
short_points.dtype
## 演示1：如何更改tensor的数据精度和类型

torch.int16

In [51]:
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()
## 演示2：对tensor数据精度和类型改变的方式

In [56]:
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)
## 演示3：对tensor数据精度和类型改变的方式

In [55]:
points = torch.randn(10, 2) 
short_points = points.type(torch.short)
## 演示4：对tensor数据精度和类型改变的方式

### tensor中高级索引的用法

In [59]:
# reset points back to original value
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [57]:
some_list = list(range(6))
some_list[:]     
some_list[1:4]   
some_list[1:]    
some_list[:4]   
some_list[:-1]   
some_list[1:4:2] 

[1, 3]

In [60]:
points[1:]       
points[1:, :]    
points[1:, 0] 

tensor([5., 2.])

In [61]:
points = torch.ones(3, 4)
points_np = points.numpy()
points_np
## 如何转换成numpy的ndarray

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [62]:
points = torch.from_numpy(points_np)
## 如何从numpy转换成pytorch tensor

In [63]:
torch.save(points, '../data/c2/ourpoints.t')
## 演示1：如何保存成二进制数据文件

In [65]:
with open('../data/c2/ourpoints.t','wb') as f:
   torch.save(points, f)
## 演示2：如何保存成二进制数据文件

In [66]:
points = torch.load('../data/c2/ourpoints.t')
## 演示1：如何读取二进制数据文件成tensor

In [68]:
import h5py

f = h5py.File('../data/c2/ourpoints.hdf5', 'w')
dset = f.create_dataset('coords', data=points.numpy())
f.close()
## 如何保存成hdf5

In [71]:
f = h5py.File('../data/c2/ourpoints.hdf5', 'r')
dset = f['coords']
last_points = dset[-2:]
## 如何从hdf5读取

In [72]:
last_points = torch.from_numpy(dset[-2:])
f.close()

In [73]:
# points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')
## 这里展示的如何把tensor转移到gpu上，目前我们的cpu版本暂不支持，有独立显卡的可以尝试

In [74]:
# points_gpu = points.to(device='cuda')

In [75]:
# points_gpu = points.to(device='cuda:0')

In [76]:
# points = 2 * points
# points_gpu = 2 * points.to(device='cuda') 

In [77]:
# points_cpu = points_gpu.to(device='cpu')

In [78]:
# points_gpu = points.cuda()
# points_gpu = points.cuda(0)
# points_cpu = points_gpu.cpu()

### tensor中几种类方法的使用，注意函数格式

In [79]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [80]:
a = torch.ones(3, 2)
a_t = a.transpose(0, 1)

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [81]:
a = torch.ones(3, 2)

In [82]:
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])